// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pkg/proto/api_yoomoney_client/api_yoomoney_client.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
}

func (x *CheckReq) Reset() {
	*x = CheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReq) ProtoMessage() {}

func (x *CheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReq.ProtoReflect.Descriptor instead.
func (*CheckReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescGZIP(), []int{0}
}

func (x *CheckReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type CheckResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
}

func (x *CheckResp) Reset() {
	*x = CheckResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResp) ProtoMessage() {}

func (x *CheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResp.ProtoReflect.Descriptor instead.
func (*CheckResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	Sum   int64  `protobuf:"varint,2,opt,name=Sum,proto3" json:"Sum,omitempty"`
}

func (x *GetURLReq) Reset() {
	*x = GetURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLReq) ProtoMessage() {}

func (x *GetURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLReq.ProtoReflect.Descriptor instead.
func (*GetURLReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetURLReq) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type GetURLResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URL string `protobuf:"bytes,1,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *GetURLResp) Reset() {
	*x = GetURLResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResp) ProtoMessage() {}

func (x *GetURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResp.ProtoReflect.Descriptor instead.
func (*GetURLResp) Descriptor() ([]byte, []int) {
	return file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescGZIP(), []int{3}
}

func (x *GetURLResp) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto protoreflect.FileDescriptor

var file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDesc = []byte{
	0x0a, 0x37, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x5f,
	0x79, 0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x5f, 0x79, 0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x70, 0x69, 0x5f, 0x79,
	0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x20, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x22, 0x1b, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x22, 0x33,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x53, 0x75, 0x6d, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x55, 0x52, 0x4c, 0x32, 0xab, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12,
	0x1e, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x79, 0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x79, 0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x4d, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x5f, 0x79, 0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e,
	0x61, 0x70, 0x69, 0x5f, 0x79, 0x6f, 0x6f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescOnce sync.Once
	file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescData = file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDesc
)

func file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescGZIP() []byte {
	file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescOnce.Do(func() {
		file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescData)
	})
	return file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDescData
}

var file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_goTypes = []interface{}{
	(*CheckReq)(nil),   // 0: api_yoomoney_service.CheckReq
	(*CheckResp)(nil),  // 1: api_yoomoney_service.CheckResp
	(*GetURLReq)(nil),  // 2: api_yoomoney_service.GetURLReq
	(*GetURLResp)(nil), // 3: api_yoomoney_service.GetURLResp
}
var file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_depIdxs = []int32{
	0, // 0: api_yoomoney_service.PaymentService.Check:input_type -> api_yoomoney_service.CheckReq
	2, // 1: api_yoomoney_service.PaymentService.GetURL:input_type -> api_yoomoney_service.GetURLReq
	1, // 2: api_yoomoney_service.PaymentService.Check:output_type -> api_yoomoney_service.CheckResp
	3, // 3: api_yoomoney_service.PaymentService.GetURL:output_type -> api_yoomoney_service.GetURLResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_init() }
func file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_init() {
	if File_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetURLResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_goTypes,
		DependencyIndexes: file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_depIdxs,
		MessageInfos:      file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_msgTypes,
	}.Build()
	File_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto = out.File
	file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_rawDesc = nil
	file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_goTypes = nil
	file_pkg_proto_api_yoomoney_client_api_yoomoney_client_proto_depIdxs = nil
}
